language: node_js
node_js:
  - "0.11.13"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - gem update --system
  - gem install sass
  - npm install -g grunt-cli